Merge branch 'bug_15492' into 'develop'
Bug #15492: Upgrading maven.dependencycheck.version to latest available version 12.1.9.

Fixing error:
```
[ERROR] Error updating the NVD Data; the NVD returned a 403 or 404 error
Consider using an NVD API Key; see https://github.com/jeremylong/DependencyCheck?tab=readme-ov-file#nvd-api-key-highly-recommended
org.owasp.dependencycheck.data.update.exception.UpdateException: Error updating the NVD Data; the NVD returned a 403 or 404 error
[ERROR] Unable to continue dependency-check analysis.
[ERROR] Fatal exception(s) analyzing vitam-parent
```

See merge request vitam/vitam!10872

(cherry picked from commit f03b00d60c79a23ec2c6a1e8ad62a43dad36091b)

ca641faa Bug #15492: Upgrading maven.dependencycheck.version to latest available version 12.1.9.

Co-authored-by: Julien Georges <julien.georges@culture.gouv.fr>